### ISSUE TITLE
Wrong current input channel displayed

### ISSUE THREAD

**Issue by senolem** [Infiziert90/ChatTwo#93]
[ChatTwo.json](https://github.com/user-attachments/files/16321536/ChatTwo.json)
Since some update, not sure which, the current input channel displayed is wrong.
For example :
If i set it to party, it would display current input channel as party
Then write a message in FC chat using `/fc blabla`, it would display my current input channel is FC.
Then if I write a message without command, it would be sent in party while it's still showing the current input channel being FC before and after sending the message.
I didn't edit anything in my chat2 configuration recently... Are you able to reproduce the issue?

**Comment by deansheather** [comment]
Just to be clear, to reproduce this:
1. `/p` or select Party in the input channel selector
2. Input says "Party"
3. `/fc blahblah`
4. Input says "Free Company"
5. `blahblah`
6. Message gets sent to party chat instead of FC chat

I tried this and can't reproduce it. Are you using a tab with an input channel set? Even if I replace step 1 with using a tab with the input channel set to "Party" I can't reproduce it.

**Comment by senolem** [comment]
The issue stops if I disable "Sticky chat" feature from Simple Tweaks, it used to work before though...
Can I achieve the same feature without it?

**Comment by Infiziert90** [comment]
Wait for simpletweaks to be updated
